### ISSUE TITLE
 ergonomy_joe has some otherwise unpublished decompilations on his personal website

### ISSUE THREAD

**Issue by hobohyperborian** [ff7man/chocobo-betting#1]
Might wanna archive these.

https://magnetiktank.blogspot.com/

edit

I archived them.

https://archive.ph/zJN46
https://archive.ph/Il3LU

**Comment by ff7man** [comment]
I made a folder with his blog, I got the zip from archive.org, and copied some projects from his github. Would be cool if he reversed the chocobo game more :)
